### ISSUE TITLE
How to customize position (e.g. top/bottom of a <div>)?

### ISSUE THREAD

**Issue by Kitanotori** [Storytel/react-redux-spinner#12]
How do I change the location of the progress bar and the spinner? Let's say I have a query `<form>`, and I want to have the spinner and the progress bar appear at the bottom of the form after user presses `<button>`. How to achieve this?

**Comment by noseglid** [comment]
The spinner/loader itself is actually [nprogress](http://ricostacruz.com/nprogress/). You can use any configuration option available by passing a config object as a property: `<Spinner config={{ trickleRate: 0.02 }} />`.

**Comment by apandichi** [comment]
To be more precise, for other lazy travelers among these plains...

You need something like this:
```
<div id='spinner'>
   <Spinner config={{ parent: '#spinner' }} />
</div>
```

If you're using [the default CSS](https://github.com/Storytel/react-redux-spinner/blob/master/src/nprogress.css), you need to comment or remove the following

```
#nprogress .spinner {
  display: block;
  position: fixed;
  z-index: 1031;
  top: 15px;
  right: 15px;
}

.nprogress-custom-parent {
  overflow: hidden;
  position: relative;
}
```

Otherwise, the spinner/loading bar will not be shown **at all**.

**Comment by noseglid** [comment]
That's it. Thanks for the example, @apandichi 👍

**Comment by kingo999** [comment]
Hi , 
Is there a way to assign an Id to a spinner ? 
For instance if I do not want to start a nother spinner if one with that Id is already running ? 
The same goes for ending the spinner, do not end if the id count is 0.
Tx
