### ISSUE TITLE
bundle file is too big

### ISSUE THREAD

**Issue by mojilla** [Storytel/react-redux-spinner#15]
hi and thanks for this repo
the build file is almost 47kb 
is there any way to reduce that ?

![capture](https://user-images.githubusercontent.com/5251461/28497733-d4dc86b8-6fa2-11e7-8324-51a765622c0e.JPG)

thanks

**Comment by arturocr** [comment]
I bet this is because it embeds nprogress sources and styles as well, which makes it a reasonable size.

**Comment by noseglid** [comment]
Hello,
Thank you for reporting this. As @arturocr it bundles `nprogress`, so the size is "reasonable".
One optimization we're looking to do is to include `nprogress` as a dependency (rather than as it is now - a `devDependency` which gets bundled in the `react-redux-spinner`.

This would only decrease the bundle size if you used `nprogress` outside of `react-redux-spinner`.

Additionally I think we could make the CSS inclusion conditional. But this would only help you decrease bundlesize if you provide your own CSS for styling.

I'll keep this issue  open to track what we can do to decrease the bundlesize.

**Comment by noseglid** [comment]
I've found some optimizations which takes it from 46K to 26K.
  * Minify CSS (duh!)
  * Update to uglifyjs v3 (ES aware)
  * Upgrade dependencies which generally had  a decreased bundlesize.

This is the bundle now:
```
Bundle: react-redux-spinner
prop-types: 24.88 KB (35.7%)
style-loader: 12.13 KB (17.4%)
nprogress: 11.29 KB (16.2%)
process: 5.17 KB (7.42%)
fbjs: 4.26 KB (6.11%)
css-loader: 2.21 KB (3.17%)
object-assign: 2.06 KB (2.95%)
<self>: 7.7 KB (11.0%)
```
